# Generated by Django 5.0.1 on 2024-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freelance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authoring",
            name="review_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="msg_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ordering",
            name="order_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
