# Generated by Django 5.0.1 on 2024-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "freelance",
            "0002_alter_authoring_review_date_alter_message_msg_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="authoring",
            name="review_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="msg_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ordering",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
