# Generated by Django 4.2.5 on 2024-02-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("desc", models.TextField(verbose_name="Описание")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("markt", "Marketing"),
                            ("copy", "Copywriting"),
                            ("rwrite", "Rewriting"),
                            ("trans", "Translating"),
                            ("video", "Video-Making"),
                            ("photo", "Photoshop"),
                        ],
                        default="web",
                        max_length=12,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
